apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes  1;
    #Referes to single threaded process. Generally set to be equal to the number of CPUs or cores.

    #error_log  logs/error.log; #error_log  logs/error.log  notice;
    #Specifies the file where server logs. 

    #pid        logs/nginx.pid;
    #nginx will write its master process ID(PID).

    events {
        worker_connections  1024;
        # worker_processes and worker_connections allows you to calculate maxclients value: 
        # max_clients = worker_processes * worker_connections
    }


    http {    
        server {
            listen 80 default_server;
            # server_name *.frankfurt.micheal.ch;
            server_name _;

            # DNS resolver for dynamic domain name resolution
            resolver 127.0.0.11 valid=10s;
            # resolver 8.8.8.8 valid=10s;
            # resolver_timeout 10s;

            location / {
                # Capture the domain name from the client's request header (Host)
                set $target_domain $host;  # Capture the domain name from the request
                # Forward the request to the backend server with HTTPS
                # The target domain for proxy_pass is dynamically set by the $target_domain variable
                proxy_pass https://$target_domain;  # Use variable for proxy_pass
                # Send the original SNI hostname to the upstream server for proper SSL handshake
                proxy_ssl_server_name on;
                # Pass the original request headers to the backend server
                proxy_pass_request_headers on;
                
                # Set or reset the following headers for the upstream server
                # Pass the original Host header
                proxy_set_header        Host            $host;
                # Pass the original client IP to the backend/backend.
                proxy_set_header        X-Real-IP       $remote_addr;
                # Pass the original X-Forwarded-For, appending the client's IP.
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                # proxy_set_header        X-Forwarded-Proto $scheme;

                # Don't change any "Location" or "Refresh" headers in responses from upstream servers
                proxy_redirect      off;
            }
        }
    }
  virtualhost.conf: |
    upstream app {
      server localhost:8080;
      keepalive 1024;
    }
    server {
      listen 80 default_server;
      root /usr/local/app;
      access_log /var/log/nginx/app.access_log main;
      error_log /var/log/nginx/app.error_log;
      location / {
        proxy_pass http://app/;
        proxy_http_version 1.1;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: default
  labels:
    app: nginx-test
spec:      

  selector:
    matchLabels:
      app: nginx-test
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      hostAliases:
      - ip: "173.44.139.215"
        hostnames:
          - "frankfurt.micheal.ch"
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx # mount nginx-conf volumn to /etc/nginx
          readOnly: true
          name: nginx-conf
        - mountPath: /var/log/nginx
          name: log
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
      volumes:

      - name: nginx-conf
        configMap:
          name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf
            - key: virtualhost.conf
              path: virtualhost/virtualhost.conf # dig directory
      - name: log
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/proxy-ssl-server-name: "on"
    #nginx.ingress.kubernetes.io/proxy-ssl-name: "https://frankfurt.micheal.ch"
    #nginx.ingress.kubernetes.io/upstream-vhost: "https://frankfurt.micheal.ch"
  name: test
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: frankfurt.micheal.ch
    http:
      paths:
      - backend:
          service:
            name: test
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - frankfurt.micheal.ch
      secretName: tls-frankurt-micheal.ch-ingress
